const booksData = [
    {
      id: 1,
      name: "JavaScript and Jquery",
      author: "Jon Duckett",
      price: 62,
      rating: 4,
      image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1394412494i/16219704.jpg',
      publicationYear: 2022,
      favourite: true,
    },
    {
      id: 2,
      name: "React Up and Running",
      author: "Stoyan Stefanov",
      price: 45,
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/71irCEhrZlL._SY425_.jpg',
      publicationYear: 2021,
      favourite: false,
    },
    {
      id: 3,
      name: "CSS Mastery",
      author: "Andy Budd",
      price: 55,
      rating: 5,
      image: 'https://m.media-amazon.com/images/I/31hu2mXMLVL._SY445_SX342_.jpg',
      publicationYear: 2020,
      favourite: true,
    },
    {
      id: 4,
      name: "Node.js in Action",
      author: "Mike Cantelon",
      price: 60,
      rating: 4.2,
      image: 'https://m.media-amazon.com/images/I/51MrPqGf+DL._SY425_.jpg',
      publicationYear: 2019,
      favourite: false,
    },
    {
      id: 5,
      name: "Eloquent JavaScript",
      author: "Marijn Haverbeke",
      price: 40,
      rating: 4.8,
      image: 'https://m.media-amazon.com/images/I/41VvIauMuuL._SY445_SX342_.jpg',
      publicationYear: 2018,
      favourite: true,
    },
    {
      id: 6,
      name: "Fullstack Open",
      author: "Matti Luukkainen",
      price: 70,
      rating: 4.7,
      image: 'https://m.media-amazon.com/images/I/51KhkPlngUL._SX342_SY445_.jpg',
      publicationYear: 2017,
      favourite: true,
    },
    {
      id: 7,
      name: "Vue.js Up and Running",
      author: "Callum Macrae",
      price: 50,
      rating: 4.4,
      image: 'https://m.media-amazon.com/images/I/71IzrlAB1dL._AC_UY218_.jpg',
      publicationYear: 2016,
      favourite: false,
    },
    {
      id: 8,
      name: "Python Crash Course",
      author: "Eric Matthes",
      price: 35,
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/41LMH8YYB0L._SX342_SY445_.jpg',
      publicationYear: 2015,
      favourite: false,
    },
    {
      id: 9,
      name: "The Pragmatic Programmer",
      author: "Andrew Hunt",
      price: 48,
      rating: 4.9,
      image: 'https://m.media-amazon.com/images/I/51yaxPX4BFL._AC_UY218_.jpg',
      publicationYear: 2014,
      favourite: false,
    },
    {
      id: 10,
      name: "Design Patterns",
      author: "Erich Gamma",
      price: 58,
      rating: 4.7,
      image: 'https://m.media-amazon.com/images/I/71SdDjMglAL._AC_UY218_.jpg',
      publicationYear: 2013,
      favourite: true,
    },
  ];
  
  export default booksData;
  